# -*- coding: utf-8 -*-
"""breast_cancer_final.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16NuzafWLHiEfoYDQPBhfpxwXye8muSI4
"""

import os
os.chdir("drive/My Drive/colab")

import xgboost as xgb
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
data=pd.read_csv("breast_cancer_data.csv")
data.drop(['id', 'Unnamed: 32'], axis = 1, inplace = True)
data.head(5)

data = data.values
x = data[ : , 1:]
y = data[ : , 0]
print(x.shape, y.shape)

x_train_val, x_test_val, y_train_val, y_test_val = train_test_split(x, y, test_size = 0.20, random_state=123)
print(x_train_val.shape,
     y_train_val.shape,
     x_test_val.shape,
     y_test_val.shape)

clf = XGBClassifier()
clf.fit(x_train_val, y_train_val)

pred = clf.predict(x_test_val)
print(pred, y_test_val, sep = '\n')

print("Accuracy of model is: ", accuracy_score(y_test_val, pred))

from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
cr = classification_report(y_test_val, pred)
print(cr)

# confusion matrix 
cm = confusion_matrix(y_test_val, pred)
plt.rcParams['figure.figsize'] = (5, 5)
sns.heatmap(cm, annot = True, cmap = 'winter')
plt.title('Confusion Matrix', fontsize = 20)
plt.show()







